// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scopes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertScope = `-- name: InsertScope :one
INSERT INTO scopes (
    "slug",
    "created_at",
    "created_by",
    "deleted_at",
    "deleted_by",
    "updated_at",
    "updated_by",
    "version"
) VALUES (
    $1, $2, $3, NULL, NULL, NULL, NULL, $4
) RETURNING id, slug, created_at, created_by, deleted_at, deleted_by, updated_at, updated_by, version
`

type InsertScopeParams struct {
	Slug      string    `db:"slug" json:"slug"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	CreatedBy uuid.UUID `db:"created_by" json:"created_by"`
	Version   int32     `db:"version" json:"version"`
}

func (q *Queries) InsertScope(ctx context.Context, arg InsertScopeParams) (Scope, error) {
	row := q.db.QueryRow(ctx, insertScope,
		arg.Slug,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.Version,
	)
	var i Scope
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.Version,
	)
	return i, err
}
